---
# Source: ibm-ace-server-icp4i-prod/templates/metrics-service-ace.yaml
# © Copyright IBM Corporation 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9483'
  name: my-integration-server-ibm-ace-server-icp4i-prod-ace-metrics
  labels:
    app.kubernetes.io/name: "ibm-ace-server-icp4i-prod"
    helm.sh/chart: "ibm-ace-server-icp4i-prod"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/instance: "my-integration-server"
    release: "my-integration-server"
    app.kubernetes.io/component: "ace-metrics"
spec:
  type: ClusterIP
  ports:
  - targetPort: 9483
    port: 9483
    protocol: TCP
  selector:
    app.kubernetes.io/name: "ibm-ace-server-icp4i-prod"
    helm.sh/chart: "ibm-ace-server-icp4i-prod"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/instance: "my-integration-server"
    release: "my-integration-server"
