---
# Source: ibm-ace-server-icp4i-prod/templates/server-role.yaml
# © Copyright IBM Corporation 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###############################################################################
# Creates a role that can list services
###############################################################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-integration-server-ibm-ace-server-icp4i-prod-role
  labels:
    app.kubernetes.io/name: "ibm-ace-server-icp4i-prod"
    helm.sh/chart: "ibm-ace-server-icp4i-prod"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/instance: "my-integration-server"
    release: "my-integration-server"
rules:
- apiGroups: [""] 
  resources: ["services"]
  verbs: ["get","list"]
- apiGroups: ["extensions"] 
  resources: ["deployments"]
  verbs: ["get","list"]
- apiGroups: ["route.openshift.io"] 
  resources: ["routes"]
  verbs: ["get","list"]