---
# Source: ibm-ace-server-icp4i-prod/templates/service.yaml
# © Copyright IBM Corporation 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  name: my-integration-server-ibm-ace-server-icp4i-prod
  labels:
    hideLaunchLink: 'true'
    app.kubernetes.io/name: "ibm-ace-server-icp4i-prod"
    helm.sh/chart: "ibm-ace-server-icp4i-prod"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/instance: "my-integration-server"
    release: "my-integration-server"
spec:
  type: ClusterIP
  ports:
  - port: 7600
    targetPort: 7600
    protocol: TCP
    name: webui
  - port: 7800
    targetPort: 7800
    protocol: TCP
    name: ace-http
  - port: 7843
    targetPort: 7843
    protocol: TCP
    name: ace-https
  # Use the following section to add custom ports to the service.
  #- port: 2000
  #  targetPort: 2000
  #  protocol: TCP
  #  name: customPort
  selector:
    app.kubernetes.io/name: "ibm-ace-server-icp4i-prod"
    helm.sh/chart: "ibm-ace-server-icp4i-prod"
    app.kubernetes.io/managed-by: "Tiller"
    app.kubernetes.io/instance: "my-integration-server"
    release: "my-integration-server"
